### ISSUE TITLE
Tool to generate intake-catalog for CESM runs

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/ecgtools#16]
Python script that is given a CESM caseroot and generates a pandas dataframe containing info of netcdf files in `DOUT_S_ROOT`

Desired columns:

* `case` [strictly speaking this isn't needed, but it could provide useful]
* `path` (determined by crawling the archive directory)
* `component` (determined by which subdirectory of `DOUT_S_ROOT` contains the file)
* `stream` (from filename)
* `variable` (from filename)
* `date_range` (from filename)
* `ctrl_branch_year` (`RUN_REFDATE`, assuming `GET_REFCASE` is `TRUE`)
* `ctrl_case` (`RUN_REFCASE`, assuming `GET_REFCASE` is `TRUE`)

**Comment by andersy005** [comment]
As an update, there's a function for harvesting metadata from a CESM time slice file:

https://github.com/NCAR/ecgtools/blob/36ffcf245aa5d123e1fec25ad1c9bdab72048f91/ecgtools/parsers/cesm.py#L79-L106

For an end-to-end example showing how to builder a catalog for a CESM run, here's a link to a complete [notebook](https://nbviewer.jupyter.org/github/NCAR/ecgtools/blob/36ffcf245aa5d123e1fec25ad1c9bdab72048f91/docs/source/cesm-history-files.ipynb)

**Comment by mgrover1** [comment]
@andersy005 can we close this now? Since we have this functionality now?

**Comment by andersy005** [comment]
Closing this as it's been addressed. The current functionality isn't perfect, but it gets the job done without relying on `CESM_postprocessing`.
