### ISSUE TITLE
[FEATURE]: Increase performance/speed to Builder.build

### ISSUE THREAD

**Issue by jsta** [NCAR/ecgtools#194]
### Is your feature request related to a problem?

I am trying to run `Builder.build` on a very large archive path and it takes a very long time.

### Describe the solution you'd like

Is there a possibility of speeding up `Builder.build` by e.g. parallelizing the directory traversals?

**Comment by kuchaale** [comment]
I am able to parse 6776 assets in 12 minutes using 4 workers which I find reasonable according to the fact that I open the NetCDF files to parse their attributes. Have you tried e.g. `joblib_parallel_kwargs=dict(n_jobs=-1)`?

**Comment by jsta** [comment]
Thanks for the tip! That did it.
