### ISSUE TITLE
confusing comment in parsers/cesm.py and duplicated code

### ISSUE THREAD

**Issue by klindsay28** [NCAR/ecgtools#47]
The following comment occurs twice in `parsers/cesm.py`:
```
# Make sure to sort the streams in reverse, the reverse=True is required so as
# not to confuse `pop.h.ecosys.nday1` and `pop.h.ecosys.nday1` when looping over
# the list of streams in the parsing function
```
I'm guessing that the stream names should differ, but it's not clear what is intended.

Also, the code block that this comment is in appears to be duplicated. Is there a reason to do this that I'm missing?

**Comment by andersy005** [comment]
Fixed in #48
